site_name: HxH Système JDR
nav:
  - Accueil: index.md
  - Armes & Armures: armes.md
theme:
  name: material
  language: fr
  palette:
    scheme: slate
plugins:
  - search
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/glossaire.md